services:
  portfolio:
    build:
      dockerfile: ./docker/Dockerfile-dev
      context: .
      args:
        HOST_USER_ID: ${HOST_USER_ID:-1000}
        HOST_GROUP_ID: ${HOST_GROUP_ID:-1000}
    ports:
      - ${SERVER_PORT:-3100}:3100
    volumes:
      - ./:/app

